### ISSUE TITLE
Who's going to install this anonymous binary? 

### ISSUE THREAD

**Issue by welly** [commandquarterly/blackpage#3]
Come on. Let us see the source code. Wouldn't touch this with a barge pole otherwise.

**Comment by stephenwithav** [comment]
Came to say the same.

**Comment by Zettersten** [comment]
Yup.

**Comment by nblackburn** [comment]
#2

**Comment by justplainc** [comment]
The code has been immediately repurposed for use in game engines and other commercial projects with a similar core framework.  Some of which I’ve even licensed to others.  In other words, I re-use my code and ship things with it frequently.  Same as many developers.  So in the words of one if my co-workers; open sourcing this entirely would be equivalent to leaving my house labeled with my full name and address out on the nearest sidewalk.  

Again, some parts will be. But I’ve been rinse and repeating the client core tech for a while now and I’m still generally destitute. This stuff is my livelihood. Now I imagine that once this has been ported over to mobile and the web the issue will seem less relevant considering our long term goals and shift in audience.

**Comment by stephenwithav** [comment]
Refactor the code then.
