### ISSUE TITLE
You might as well open your code...

### ISSUE THREAD

**Issue by ekollof** [commandquarterly/blackpage#6]
```sh
[ekollof][beeblebrox][±][master ?:2 ✗][~/.../blackpage/linux_x64]
$ file blackpage 
blackpage: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=39ceb84e48c3e5263d0e3499097265c704c793e6, not stripped
[ekollof][beeblebrox][±][master ?:2 ✗][~/.../blackpage/linux_x64]
$ objdump -d blackpage > blackpage.S
```
The "not stripped" above implies that all the symbols are still in the executable image. You might as well ship source code. 

And thanks to the versioning nature of git, it will always be available.

**Comment by justplainc** [comment]
Hey thanks for the feedback.  Well the project was an attempt at crowdfunding a year of hosting with plans to slowly roll out the source over time although things would need to be changed.  So no real secrets here although there are pretty straightforward reasons as to why it’s not. As mentioned previously, in the event the campaign was not successful the projects source would essentially be used as for it’s original purpose.  Which is the be a social component to online games.  I’ve said this before but thought I should elaborate this time so check this out:

https://youtu.be/-hAqI1Nsasw

Blackpage, funny enough is a stripped down version of a commercial game engine.  And so the plan now is to simply merge it back.  Another reason it’s been severed from the “body” was to allow for working on it without the integration code in place. This also made it easier to add features, anything really.

Anyway I’ll be taking this down today to avoid confusion.  Funny enough, I had just gotten busy with the aforementioned re-attachment to the primary sources.  Besides and frankly, if I can’t personally afford a $4 VPS I probably shouldn’t be giving away years of work for free.
